// Snowpack Configuration File
// Automatically Generated by Head-start
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: { src: '/' },
  plugins: [ '@snowpack/plugin-sass' ],
  packageOptions: {},
  devOptions: { out: 'test' },
  buildOptions: { out: 'dist' },
  exclude: [ '**/node_modules/**/*' ]
}