// Snowpack Configuration File for the React.js Framework
// Generated by Head-start

/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: {
    public: { url: "/", static: true },
    src: { url: "/dist" },
  },
  plugins: ["@snowpack/plugin-sass"],
  packageOptions: {
    /* ... */
  },
  devOptions: {
    out: "test",
  },
  buildOptions: {
    out: "dist",
  },
  exclude: ["**/node_modules/**/*"],
};
