name: Testing
on:
  # Only run on pushes to the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      branch_name: "$(echo 'hello')"
    steps:
      - name: checkout main branch into the setup/ directory
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
      # Set the node.js version
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.x
      - name: Get values from NPM
        run: echo "branch_name=$(npm run-script branch)" >> $GITHUB_ENV
      - name: Echo values from NPM
        run: echo "the branch name is ${{env.branch_name}}"
