name: Testing
on:
  # Only run on pushes to the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      branch_name: nothing
    steps:
      - name: checkout main branch into the setup/ directory
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
      # Set the node.js version
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.x
      - name: Get values from NPM
        run: |
          npm run-script branch-name >> $branch_name
          echo "the branch name is $branch_name"
