name: GitHub Node.js Deploy
on:
  # Only run on pushes to the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
      # Set the node.js version
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"
      - run: npm --version
      - run: ls
      - name: setup npm
        run: |
          git branch -D dev &>/dev/null || true
          npm run test
          mv temp/ new/
          rm -rf build/node_modules/
          ls
      - name: Commit files for change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local advice.addIgnoredFile false
          git config --local add.ignoreErrors true
          git add new/
          git commit --only new/ --message "Pushed brand-new site files"
          git push origin dev
      # push files into `gh-pages` branch
