name: GitHub Node.js Deploy
on:
  # Only run on pushes to the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
      # Set the node.js version
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"
      - run: npm --version
      - name: setup npm
        run: |
          cd temp
          npm ci
          npm run deployment-branch >> $GITHUB_ENV
          echo "${{ env.deployment-branch }}"