name: GitHub Pages Deploy
env:
  input_branch: main
  output_branch: dev
on:
  # Only run on pushes to the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup from previous run
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: "Artifact Cleanup"
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
  checkout-dev:
    name: Checkout the dev branch
    needs:
      - cleanup
    runs-on: ubuntu-latest
    steps:
      # checkout our output branch
      - name: checkout output branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.output_branch }}
          persist-credentials: false
      # we can run any git sanity checks, to make sure that everything is up to par

      # once the above tests have passed, we'll upload the branch we checked out to a workflow artifact so that other
      # jobs can access its results too.
      - name: Upload checkout to workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: checkout-output-artifact
          path: .
          retention-days: 1
          if-no-files-found: warn
  checkout-main:
    name: Checkout the main branch
    needs:
      - cleanup
    runs-on: ubuntu-latest
    steps:
      # checkout our input branch
      - name: checkout input branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.input_branch }}
          persist-credentials: false
      # we can run any git sanity checks, to make sure that everything is up to par

      # once the above tests have passed, we'll upload the branch we checked out to a workflow artifact so that other
      # jobs can access its results too.
      - name: Upload checkout to workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: checkout-input-artifact
          path: .
          retention-days: 1
          if-no-files-found: warn
  build:
    name: Build our Branch
    needs: [checkout-dev, checkout-main]
    runs-on: ubuntu-latest
    steps:
      # Download the artifact from the previous job ('checkout-dev')
      - name: Download our checkout-dev artifact
        uses: actions/download-artifact@v2
        with:
          name: checkout-output-artifact
      # Download the artifact from the previous job ('checkout-main')
      - name: Download our checkout-main artifact
        uses: actions/download-artifact@v2
        with:
          name: checkout-input-artifact
          path: out
      # Set the node.js version
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.x

      # Get the current versions of node and npm
      - run: node --version
      - run: npm --version

      - name: Compile Site
        run: |
          cd out
          npm run-script compile

      - name: Upload build output to workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output-artifact
          path: .
          retention-days: 1
          if-no-files-found: warn
  deploy:
    name: Deploy to branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download our build output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output-artifact
      # commit changes
      - name: Commit files for change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --message "Pushed brand-new site files" --allow-empty
      # push files into `gh-pages` branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: ${{ env.output_branch }}
          force: true
